window.CONTRIBUTE_HOST = 'http://localhost:4001'
window.GTM_ID = ''
window.DISC_API_URL = 'http://localhost:4000'
window.DISC_UI_URL = 'https://www.example.com'
window.STREETS_TILE_LAYER_URL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
window.LOGO_URL = 'https://placekitten.com/530/530'
window.FOOTER_LEFT_SIDE_TEXT = '© 2022 UrbanOS. All rights reserved.'
window.FOOTER_LEFT_SIDE_LINK = 'https://github.com/UrbanOS-Public/discovery_ui'
window.FOOTER_RIGHT_LINKS = "[{\"linkText\":\"Example 1\", \"url\":\"https://www.example.com\"}, {\"linkText\":\"Example 2\", \"url\":\"https://www.google.com\"}]"
window.HEADER_TITLE = 'UrbanOS Data Discovery'
// omitting mapbox will default plot.ly to use openstreetmap.org
window.MAPBOX_ACCESS_TOKEN = ''
window.AUTH0_DOMAIN = 'urbanos-dev.us.auth0.com'
window.AUTH0_CLIENT_ID = 'SHqaonqYEYiS4El57rGHplqLMG00pQKR'
window.AUTH0_AUDIENCE = 'discovery_api'
window.REQUIRE_API_KEY = 'false'
window.REGENERATE_API_KEY_FF = 'true'
window.PRIMARY_COLOR = '#28807C'