name: Docker publish

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:
env:
  GITHUB_BRANCH: ${{ github.event.release.tag_name }}
  DOCKER_USERNAME: ${{ secrets.docker_username }}
  DOCKER_PASSWORD: ${{ secrets.docker_password }}
  QUAY_USERNAME: ${{ secrets.quay_username }}
  QUAY_PASSWORD: ${{ secrets.quay_password }}
jobs:
  dev:
    name: Publish Development Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t discovery_ui:build .
      - name: Publish Dev Image
        run: bash scripts/deploy.sh master
      - name: Publish to Quay
        run: bash scripts/quay.sh discovery_ui development

  release:
    name: Release Image
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t discovery_ui:build .
      - name: Publish Tagged Image
        run: bash scripts/deploy.sh release
