name: Docker test

on:
  pull_request:
    branches:
      - main

jobs:
  dev:
    name: Test Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build .
